org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=logisticsnetworks
mod_name=LogisticsNetworks
mod_license=All Rights Reserved
mod_version=2.0.0
mod_group_id=me.almana
mod_authors=AlmanX21
mod_description=High level, extremely lag friendly logistics mod