minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21.1.219,22)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
jei_version=19.27.0.340
mekanism_version=1.21.1-10.7.18.84
ars_nouveau_version=5.11.2.1298
jade_version=15.10.0+neoforge
ae2_version=19.2.17
ftb_teams_version=2101.1.0
emi_version=1.1.22+1.21.1
guideme_version=21.1.1
